version: '3.8'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"  # Bind port 8080 to the host
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disable setup wizard
      - JENKINS_OPTS=--httpPort=8080  # Explicitly set Jenkins to use port 8080
    restart: unless-stopped
    entrypoint: ["/bin/tini", "--", "/usr/local/bin/disable-csrf.sh"]  # Use custom entrypoint
    command: ["jenkins.sh"]  # Start Jenkins

volumes:
  jenkins_home:  # Define volume for Jenkins data