name: CI/CD Pipeline

on:
  repository_dispatch:
    types: [trigger-pipeline]

jobs:
  add-interactive-elements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Deployment-Impact-Tracker
        uses: actions/checkout@v3
        with:
          repository: vishwajeet075/Deployment-Impact-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Deployment-Impact-Tracker repository checked out successfully"

      - name: Add interactive elements to index.html
        id: add-elements
        run: |
          echo "Starting to add interactive elements to index.html..."
          
          # Define interactive elements
          interactive_elements=$(cat <<'END'
          <!-- Feedback Icon -->
          <li class="nav-item">
            <a class="nav-link feedback-icon" href="#" onclick="showFeedbackPopup()">
              <i class="fas fa-comment-dots"></i> Feedback
            </a>
          </li>

          <!-- Feedback Popup -->
          <div class="feedback-popup">
            <div class="popup-content">
              <h3>Give Feedback</h3>
              <p>We'd love to hear your thoughts!</p>
              <button onclick="hideFeedbackPopup()">Close</button>
            </div>
          </div>

          <style>
            .feedback-icon {
              color: #4F46E5;
              font-weight: bold;
            }
            .feedback-popup {
              display: none;
              position: fixed;
              top: 50%;
              left: 50%;
              transform: translate(-50%, -50%);
              background: white;
              padding: 20px;
              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
              z-index: 1000;
            }
          </style>

          <script>
            function showFeedbackPopup() {
              document.querySelector('.feedback-popup').style.display = 'block';
            }
            function hideFeedbackPopup() {
              document.querySelector('.feedback-popup').style.display = 'none';
            }
          </script>
          END
          )

          echo "Interactive elements defined. Injecting into index.html..."

          # Inject elements into the navbar
          if sed -i '/<nav class="navbar">/,/<\/nav>/ {/<\/nav>/i\'"$interactive_elements"'\n}' index.html; then
            echo "Interactive elements injected successfully!"
          else
            echo "ERROR: Failed to inject interactive elements"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          echo "Preparing to commit and push changes..."
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          else
            echo "Changes detected. Committing and pushing..."
            git add index.html
            git commit -m "Added interactive feedback elements [skip ci]"
            git push
            echo "Changes pushed successfully!"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}