name: CI/CD Pipeline

on:
  repository_dispatch:
    types: [trigger-pipeline]

jobs:
  add-interactive-elements:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Code checked out successfully"

      - name: Add interactive elements to index.html
        id: add-elements
        run: |
          echo "Starting to add interactive elements to index.html..."
          
          # Define interactive elements
          interactive_elements=$(cat <<'END'
          <!-- YOUR INTERACTIVE ELEMENTS CODE HERE -->
          END
          )

          echo "Interactive elements defined. Injecting into index.html..."

          # Inject elements before closing body tag
          if sed -i "s|</body>|${interactive_elements//$'\n'/\\n}</body>|" index.html; then
            echo "Interactive elements injected successfully!"
          else
            echo "ERROR: Failed to inject interactive elements"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          echo "Preparing to commit and push changes..."
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          else
            echo "Changes detected. Committing and pushing..."
            git add index.html
            git commit -m "Added interactive feedback elements [skip ci]"
            git push
            echo "Changes pushed successfully!"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    post:
      - name: Success Notification
        if: success()
        run: echo "Pipeline succeeded! Interactive elements added and changes pushed to GitHub."
      
      - name: Failure Notification
        if: failure()
        run: echo "Pipeline failed! Check the logs for errors."