name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  add-feedback-button:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for script execution)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Add feedback button to index.html
        run: |
          # Define the interactive elements to add
          interactive_elements='''
          <style>
            /* Add your CSS styles here */
            .feedback-button {
              position: fixed;
              bottom: 30px;
              right: 30px;
              background: linear-gradient(135deg, #6366F1, #4F46E5);
              color: white;
              padding: 15px 25px;
              border-radius: 50px;
              font-weight: 600;
              box-shadow: 0 4px 15px rgba(79, 70, 229, 0.3);
              transition: all 0.3s ease;
              z-index: 1000;
              cursor: pointer;
              display: flex;
              align-items: center;
              gap: 8px;
            }
            .feedback-button:hover {
              transform: translateY(-2px);
              box-shadow: 0 6px 20px rgba(79, 70, 229, 0.4);
            }
          </style>

          <!-- Feedback Button -->
          <div class="feedback-button" onclick="window.location.href='https://your-dashboard-url.com/feedback'">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>
            </svg>
            Give Feedback
          </div>
          '''

          # Insert the interactive elements before the closing body tag
          sed -i "s|</body>|$interactive_elements</body>|" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Added interactive feedback elements [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication